{{- if .Values.storage.createCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.credentialsSecret }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dr-core.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.storage.credentials }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
