{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dr-core.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dr-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dr-core.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
    path: /metrics
{{- end }}
{{- end }}
